# Netlify configuration file

[build]
  publish = "/"
  command = "echo 'No build needed - static site'"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self' https: 'unsafe-inline' 'unsafe-eval' https://gartin-wifi-api.onrender.com; img-src 'self' https: data:; font-src 'self' https: data:;"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Force HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://gartin-wifi-api.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = true

[build.environment]
  NODE_VERSION = "18"

# Ignore server directories during build
[build.ignore]
  command = "git diff --quiet HEAD^ HEAD ./server/ ./server-api/ ./admin-dashboard/"
